# Generated by Django 4.2.1 on 2023-06-23 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
